#coding=utf-8

import uter
import unittest

class test_case_string(unittest.TestCase):
    def test_string_get_01(self):
        arraytype = uter.array(uter.uchar, 10)
        arraydata = arraytype()
        arraydata[0]._SetValue(ord("H"))
        arraydata[1]._SetValue(ord("e"))
        arraydata[2]._SetValue(ord("l"))
        arraydata[3]._SetValue(ord("l"))
        arraydata[4]._SetValue(ord("o"))
        arraydata[5]._SetValue(0)
        getstr = uter.string.ascii.get(arraydata._GetAddress())
        self.assertEqual("Hello", getstr, "")

    def test_string_get_02(self):
        arraytype = uter.array(uter.uchar, 10)
        arraydata = arraytype()
        arraydata[0]._SetValue(ord("H"))
        arraydata[1]._SetValue(ord("e"))
        arraydata[2]._SetValue(ord("l"))
        arraydata[3]._SetValue(ord("l"))
        arraydata[4]._SetValue(ord("o"))
        arraydata[5]._SetValue(0)
        getstr = uter.string.ascii.get(arraydata._GetAddress(), 3)
        self.assertEqual("Hel", getstr, "")

    def test_string_set_01(self):
        arraytype = uter.array(uter.uchar, 10)
        arraydata = arraytype()
        arraydata[0]._SetValue(255)
        arraydata[1]._SetValue(255)
        arraydata[2]._SetValue(255)
        arraydata[3]._SetValue(255)
        arraydata[4]._SetValue(255)
        arraydata[5]._SetValue(255)
        arraydata[6]._SetValue(255)
        arraydata[7]._SetValue(255)
        arraydata[8]._SetValue(255)
        arraydata[9]._SetValue(255)
        uter.string.ascii.set(arraydata._GetAddress(), "Hello")
        self.assertEqual(True, arraydata[0]._GetValue() == ord("H"), "")
        self.assertEqual(True, arraydata[1]._GetValue() == ord("e"), "")
        self.assertEqual(True, arraydata[2]._GetValue() == ord("l"), "")
        self.assertEqual(True, arraydata[3]._GetValue() == ord("l"), "")
        self.assertEqual(True, arraydata[4]._GetValue() == ord("o"), "")
        self.assertEqual(True, arraydata[5]._GetValue() == 0, "")
        self.assertEqual(True, arraydata[6]._GetValue() == 255, "")
        self.assertEqual(True, arraydata[7]._GetValue() == 255, "")
        self.assertEqual(True, arraydata[8]._GetValue() == 255, "")
        self.assertEqual(True, arraydata[9]._GetValue() == 255, "")
        
    def test_string_set_02(self):
        arraytype = uter.array(uter.uchar, 10)
        arraydata = arraytype()
        arraydata[0]._SetValue(255)
        arraydata[1]._SetValue(255)
        arraydata[2]._SetValue(255)
        arraydata[3]._SetValue(255)
        arraydata[4]._SetValue(255)
        arraydata[5]._SetValue(255)
        arraydata[6]._SetValue(255)
        arraydata[7]._SetValue(255)
        arraydata[8]._SetValue(255)
        arraydata[9]._SetValue(255)
        uter.string.ascii.set(arraydata._GetAddress(), "Hello", 3)
        self.assertEqual(True, arraydata[0]._GetValue() == ord("H"), "")
        self.assertEqual(True, arraydata[1]._GetValue() == ord("e"), "")
        self.assertEqual(True, arraydata[2]._GetValue() == ord("l"), "")
        self.assertEqual(True, arraydata[3]._GetValue() == 255, "")
        self.assertEqual(True, arraydata[4]._GetValue() == 255, "")
        self.assertEqual(True, arraydata[5]._GetValue() == 255, "")
        self.assertEqual(True, arraydata[6]._GetValue() == 255, "")
        self.assertEqual(True, arraydata[7]._GetValue() == 255, "")
        self.assertEqual(True, arraydata[8]._GetValue() == 255, "")
        self.assertEqual(True, arraydata[9]._GetValue() == 255, "")
        